-- Create new table for one-off activities
create table public.aktivity (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  osoba_id bigint references public.osoby(id) on delete cascade not null,
  datum date not null,
  typ text not null, -- 'zapas_cks', 'zapas_int', etc.
  popis text,
  kredity integer default 0 -- store the base value (3 or 5)
);

-- Enable RLS
alter table public.aktivity enable row level security;

-- Policies (copying logic from cinnosti/licence)

-- 1. Everyone can read (public profile visibility)
create policy "Public visibility"
  on public.aktivity for select
  using ( true );

-- 2. Admins and Owners can insert/update/delete
create policy "Admins and Owners can modify"
  on public.aktivity for all
  using ( 
    auth.uid() in (
      select auth_id from public.osoby where is_admin = true
    ) 
    or 
    auth.uid() in (
      select auth_id from public.osoby where id = osoba_id
    )
  );
