-- 1. Tabulka AKCE (Events)
create table public.akce (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  nazev text not null,
  popis text,
  datum_od timestamp with time zone not null,
  datum_do timestamp with time zone,
  misto text,
  typ text not null, -- 'skoleni', 'seminar', 'turnaj', 'ine'
  kredity integer default 0,
  kapacita integer,
  cena integer default 0,
  organizator text
);

-- 2. Tabulka PŘIHLÁŠKY (Registrations)
create table public.prihlasky (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  akce_id bigint references public.akce(id) on delete cascade not null,
  osoba_id bigint references public.osoby(id) on delete cascade not null,
  status text default 'prihlasen', -- 'prihlasen', 'nahradnik', 'zruseno'
  poznamka text,
  unique(akce_id, osoba_id) -- Jedna osoba se nemůže přihlásit dvakrát na stejnou akci
);

-- 3. RLS Policies (Bezpečnost)

-- Povolit RLS
alter table public.akce enable row level security;
alter table public.prihlasky enable row level security;

-- AKCE:
-- Každý může číst (vidět) akce
create policy "Akce jsou viditelné pro všechny"
  on public.akce for select
  using (true);

-- Jen admin může vytvářet/upravovat/mazat akce
-- (Předpokládáme, že existuje funkce nebo claim 'is_admin', nebo kontrolujeme tabulku osoby podle auth.uid())
-- Pro zjednodušení zde použijeme kontrolu, zda je uživatel přihlášen, 
-- ale v reálu by aplikace měla kontrolovat roli. 
-- Zde zatím povolíme insert/update pro authenticated a spoléháme na UI/Backend logiku, 
-- NEBO lépe: použijeme existující logiku z projektu, pokud tam je.
-- Vzhledem k předchozímu kódu (AdminDashboard) se role kontroluje v aplikaci.
-- Pro DB level security bychom potřebovali vědět, jak přesně jsou admini v DB označeni (sloupec 'role' v tabulce 'osoby').

create policy "Jen admin může spravovat akce"
  on public.akce for all
  using (
    exists (
      select 1 from public.osoby
      where osoby.auth_id = auth.uid() and osoby.role = 'admin'
    )
  );

-- PŘIHLÁŠKY:
-- Uživatel vidí své přihlášky
create policy "Uživatel vidí své přihlášky"
  on public.prihlasky for select
  using (
    auth.uid() in (select auth_id from public.osoby where id = prihlasky.osoba_id)
  );

-- Admin vidí všechny přihlášky
create policy "Admin vidí všechny přihlášky"
  on public.prihlasky for select
  using (
    exists (
      select 1 from public.osoby
      where osoby.auth_id = auth.uid() and osoby.role = 'admin'
    )
  );

-- Uživatel může vytvořit přihlášku (sám za sebe)
create policy "Uživatel se může přihlásit"
  on public.prihlasky for insert
  with check (
    auth.uid() in (select auth_id from public.osoby where id = prihlasky.osoba_id)
  );

-- Uživatel může zrušit (upravit status) svou přihlášku
create policy "Uživatel může upravit svou přihlášku"
  on public.prihlasky for update
  using (
    auth.uid() in (select auth_id from public.osoby where id = prihlasky.osoba_id)
  );

-- Admin může spravovat všechny přihlášky
create policy "Admin může spravovat přihlášky"
  on public.prihlasky for all
  using (
    exists (
      select 1 from public.osoby
      where osoby.auth_id = auth.uid() and osoby.role = 'admin'
    )
  );
